#pragma once

// Generated by tools/write_overdrive_voicing_header.py.
// Edit tools/overdrive_voicing_state.json, then regenerate this file.

namespace OverdriveVoicing
{
struct Ts808CoreTuning
{
    float driveScale;
    float driveHeadroom;
    float inputGainDb;
    float solverKneeStart;
    float solverPreConduct;
    float inputHighPassHz;
    float feedbackPoleMinHz;
    float upperMidSplitHz;
    float lowTrimAtMaxDrive;
    float loopDriveMax;
    float loopCappedGainAtMaxDrive;
    float airGainAtMaxDrive;
    float loopCoeffHzLo;
    float loopCoeffHzHi;
    float bodyLimitLo;
    float bodyLimitHi;
    float bodyFeedbackLo;
    float bodyFeedbackHi;
    float bodyHardnessLo;
    float bodyHardnessHi;
    float bodyAsymmetryLo;
    float bodyAsymmetryHi;
    float upperLimitLo;
    float upperLimitHi;
    float upperFeedbackLo;
    float upperFeedbackHi;
    float upperHardnessLo;
    float upperHardnessHi;
    float upperAsymmetryScale;
    float upperDynamicFeedback;
    float upperMidDynamicFeedback;
    float upperAirDynamicFeedback;
    float upperBlendLo;
    float upperBlendHi;
    float upperAirTrimLo;
    float upperAirTrimHi;
    float legacyKneeRangeLo;
    float legacyKneeRangeHi;
};

static constexpr bool kTs808ResidualMatchingEnabled = true;
static constexpr bool kTs808BaseVoicingEnabled = false;
static constexpr bool kTs808PostHiCutEnabled = false;

static constexpr Ts808CoreTuning kTs808Core =
{
    0.8041275f,
    1.0f,
    1.25f,
    0.4f,
    0.17853419f,
    720.0f,
    5600.0f,
    3200.0f,
    0.22f,
    72.112749f,
    3.08f,
    0.32f,
    950.0f,
    680.0f,
    1.72f,
    0.48f,
    0.75f,
    3.08896f,
    0.95f,
    1.85f,
    0.08f,
    0.29f,
    3.1f,
    1.35f,
    0.55f,
    0.68208f,
    0.6f,
    0.357f,
    0.5f,
    1.0f,
    1.0f,
    1.12f,
    0.28f,
    0.46f,
    0.94f,
    0.88f,
    0.56f,
    0.99f
};

struct KlonCoreTuning
{
    float driveScale;
    float inputGainDb;
    float driveGainScale;
    float driveGainMaxScale;
    float diodeHeadroomScale;
    float softBlendScale;
    float cleanAmountScale;
    float dirtyLowMixScale;
    float dirtyToneOffset;
    float postAsymScale;
    float cleanFreqScale;
    float dirtyLowFreqScale;
    float dirtyFreqScale;
    float dirtyAmountScale;
};

static constexpr KlonCoreTuning kKlonCore =
{
    0.9063f,
    5.25f,
    1.0f,
    1.0f,
    1.213056f,
    1.08f,
    1.0662202f,
    1.4439472f,
    0.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f
};

static constexpr KlonEqBandSpec kTs808PreA[] =
{
    { KlonEqKind::LowShelf, 95.0f, 0.7f, -1.05f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 0.75f, -1.125f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 740.0f, 1.0f, 2.75f, 1, KlonEqAmount::Fixed },
};

static constexpr KlonEqBandSpec kTs808PreNdsp[] =
{
    { KlonEqKind::LowShelf, 65.0f, 0.707f, 0.125f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 125.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 500.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 2000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 4000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 8000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 0.707f, 0.0f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kTs808PreB[] =
{
    { KlonEqKind::HighShelf, 1000.0f, 0.5f, -0.5f, 1, KlonEqAmount::Classic },
    { KlonEqKind::LowShelf, 95.0f, 0.707f, -1.0f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kTs808PostCore[] =
{
    { KlonEqKind::LowShelf, 110.0f, 0.35f, -6.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 920.0f, 1.05f, 1.65f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1900.0f, 0.85f, -1.85f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 4100.0f, 0.9f, 1.65f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 8600.0f, 0.95f, -3.2f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 14500.0f, 0.707f, 1.6f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kTs808PostA[] =
{
    { KlonEqKind::HighShelf, 10000.0f, 1.5f, -2.8159421f, 1, KlonEqAmount::Classic },
    { KlonEqKind::TiltShelf, 1000.0f, 1.25f, 1.0478878f, 1, KlonEqAmount::Classic },
    { KlonEqKind::LowShelf, 95.0f, 1.25f, -1.1352952f, 2, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kTs808PostNdsp[] =
{
    { KlonEqKind::LowShelf, 65.0f, 0.707f, -2.5805525f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 125.0f, 1.0f, -2.5892324f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 1.0f, -1.5587961f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 500.0f, 1.0f, -1.7061732f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1000.0f, 1.0f, -0.91820591f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 2000.0f, 1.0f, -0.56369199f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 4000.0f, 1.0f, -2.2152814f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 8000.0f, 1.0f, -3.0402205f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 0.707f, -3.3691877f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kTs808PostB[] =
{
    { KlonEqKind::HighShelf, 10000.0f, 1.25f, -2.3850036f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::LowShelf, 250.0f, 1.5f, -1.0155605f, 2, KlonEqAmount::Fixed },
};

static constexpr KlonEqBandSpec kTs808PostHiCut =
    { KlonEqKind::LowPass, 18000.0f, 0.707f, 0.0f, 1, KlonEqAmount::Classic };

static constexpr bool kKlonResidualMatchingEnabled = true;

static constexpr KlonEqBandSpec kKlonPreA[] =
{
    { KlonEqKind::LowShelf, 129.0f, 0.7f, 1.175f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 0.75f, -1.25f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 0.75f, -1.0f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kKlonPreNdsp[] =
{
    { KlonEqKind::LowShelf, 65.0f, 0.707f, 0.75f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 125.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 500.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1000.0f, 1.0f, 0.0625f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 2000.0f, 1.0f, -0.5f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 4000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 8000.0f, 1.0f, 0.0f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 0.707f, 0.0f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kKlonPreB[] =
{
    { KlonEqKind::Peak, 1740.0f, 3.2f, 2.7f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::LowShelf, 65.0f, 0.707f, -1.0f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kKlonPostA[] =
{
    { KlonEqKind::HighShelf, 5000.0f, 1.0f, -6.5514939f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1400.0f, 3.0f, -1.8820005f, 2, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 2.0f, 1.9451703f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kKlonPostNdsp[] =
{
    { KlonEqKind::LowShelf, 65.0f, 0.707f, 2.3912063f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 125.0f, 1.0f, -1.8058387f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 250.0f, 1.0f, -3.0599713f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 500.0f, 1.0f, -4.6769892f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 1000.0f, 1.0f, -6.3674233f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 2000.0f, 1.0f, -7.3406993f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 4000.0f, 1.0f, -6.9564159f, 1, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 8000.0f, 1.0f, -5.3391775f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 0.707f, -5.5118604f, 1, KlonEqAmount::Classic },
};

static constexpr KlonEqBandSpec kKlonPostB[] =
{
    { KlonEqKind::LowShelf, 125.0f, 0.5f, -6.1408023f, 1, KlonEqAmount::Classic },
    { KlonEqKind::HighShelf, 16000.0f, 0.5f, -8.7831355f, 2, KlonEqAmount::Classic },
    { KlonEqKind::Peak, 5600.0f, 1.0f, 1.2691839f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::LowShelf, 65.0f, 0.707f, 1.9645063f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 2000.0f, 1.0f, -2.4045099f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 4000.0f, 1.0f, -2.9357786f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::TiltShelf, 1600.0f, 1.25f, -1.4600635f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::LowShelf, 65.0f, 0.707f, -1.494562f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 250.0f, 1.0f, 1.7415598f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 500.0f, 1.0f, 3.1477818f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 1000.0f, 1.0f, 5.8291289f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 2000.0f, 1.0f, 4.1927212f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 4000.0f, 1.0f, 1.9470219f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 1000.0f, 3.0f, 1.0849883f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 125.0f, 3.0f, -1.0025523f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::LowShelf, 65.0f, 0.707f, 1.765597f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 250.0f, 1.0f, -2.9240128f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 500.0f, 1.0f, -3.5228884f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 1000.0f, 1.0f, -5.7190721f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 2000.0f, 1.0f, -3.1698237f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::HighShelf, 3500.0f, 3.0f, 0.39321061f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 2800.0f, 3.0f, 0.65570261f, 2, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 250.0f, 1.0f, 1.4043989f, 1, KlonEqAmount::Fixed },
    { KlonEqKind::Peak, 4000.0f, 1.0f, -1.9426386f, 1, KlonEqAmount::Fixed },
};

} // namespace OverdriveVoicing
